### PERSONAS

GET http://localhost:3080/personas

###

POST http://localhost:3080/personas
Content-Type: application/json

{
    "idPersona": 1,
    "nombre": "Sebas",
    "apellido": "Camayo",
    "tipoDocumento": "DNI",
    "dni": 123126781,
    "rol": 2,
    "email": "ltorres@gmail.com",
    "password": "ltorres"
}